# Generated by Django 4.2.9 on 2024-01-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_recomendation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='images',
            field=models.ImageField(upload_to='restaurant/static/images'),
        ),
    ]
