# Generated by Django 4.2.9 on 2024-01-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menuitems_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='image_path',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
    ]
